import { Zone } from "./types";
import { getRawXForVisualLeft, getRawYForVisualBottom } from "./constants";

const ROW_0_Y = 360; // visual bottom line
const ROW_1_Y = 740;
const ROW_2_Y = 1120;

export const ZONES: Zone[] = [
  // ROW 0
  {
    id: "baker",
    label: "La Boulangerie",
    npcName: "Marie Dupont",
    x: getRawXForVisualLeft(151, "boulangerie"),
    y: getRawYForVisualBottom(ROW_0_Y, "boulangerie"),
    width: 280,
    height: 280,
    color: 0x8b5a2b,
    hoverColor: 0xa0703a,
    borderColor: 0x4a6fa5,
    icon: "🍞",
    category: "original",
    buildingType: "boulangerie",
  },
  {
    id: "guard",
    label: "Poste de Garde",
    npcName: "Capitaine Renard",
    x: getRawXForVisualLeft(1028, "guard_post"),
    y: getRawYForVisualBottom(ROW_0_Y, "guard_post"),
    width: 280,
    height: 280,
    color: 0x2c3e6b,
    hoverColor: 0x3a5080,
    borderColor: 0x4a6fa5,
    icon: "⚔️",
    category: "original",
    buildingType: "guard_post",
  },
  {
    id: "tavern_keeper",
    label: "Taverne du Palais-Royal",
    npcName: "Jacques Moreau",
    x: getRawXForVisualLeft(840, "tavern"),
    y: getRawYForVisualBottom(ROW_0_Y, "tavern"),
    width: 280,
    height: 280,
    color: 0x6b2c2c,
    hoverColor: 0x803a3a,
    borderColor: 0x4a6fa5,
    icon: "🍷",
    category: "original",
    buildingType: "tavern",
  },

  // ROW 1
  {
    id: "inspector",
    label: "Préfecture / Sûreté",
    npcName: "Inspecteur Gaston Lefèvre",
    x: getRawXForVisualLeft(840, "prefecture"),
    y: getRawYForVisualBottom(ROW_1_Y, "prefecture"),
    width: 280,
    height: 280,
    color: 0x2c4a6b,
    hoverColor: 0x3a5a80,
    borderColor: 0xd4af37,
    icon: "🔍",
    category: "belle_epoque",
    buildingType: "prefecture",
  },

  // ROW 2
  {
    id: "cabaret_dancer",
    label: "Le Moulin Rouge",
    npcName: "Colette Marchand",
    x: getRawXForVisualLeft(450, "cabaret"),
    y: getRawYForVisualBottom(ROW_2_Y, "cabaret"),
    width: 280,
    height: 280,
    color: 0x6b2c4a,
    hoverColor: 0x803a5a,
    borderColor: 0xd4af37,
    icon: "💃",
    category: "belle_epoque",
    buildingType: "cabaret",
  },
  {
    id: "artist",
    label: "Montmartre Atelier",
    npcName: "Henri Toulouse",
    x: getRawXForVisualLeft(919, "atelier"),
    y: getRawYForVisualBottom(ROW_2_Y, "atelier"),
    width: 280,
    height: 280,
    color: 0x4a3a2c,
    hoverColor: 0x5a4a3a,
    borderColor: 0xd4af37,
    icon: "🎨",
    category: "belle_epoque",
    buildingType: "atelier",
  },

  // Person NPCs sprinkled in streets/parks
  {
    id: "person_passerby",
    label: "Un Passant",
    npcName: "Un passant",
    x: 600,
    y: 390,
    width: 60,
    height: 60,
    color: 0x4a4a4a,
    hoverColor: 0x5a5a5a,
    borderColor: 0x888888,
    icon: "🚶",
    category: "person",
    greeting: "Good day! Lovely weather, is it not?",
  },
  {
    id: "person_shopkeeper",
    label: "Une Marchande",
    npcName: "Une marchande",
    x: 400,
    y: 770,
    width: 60,
    height: 60,
    color: 0x4a4a4a,
    hoverColor: 0x5a5a5a,
    borderColor: 0x888888,
    icon: "🛒",
    category: "person",
    greeting: "Good morning! Buy my flowers...",
  },
  {
    id: "person_flaneur",
    label: "Un Flâneur",
    npcName: "Un flâneur",
    x: 600,
    y: 1120,
    width: 60,
    height: 60,
    color: 0x4a4a4a,
    hoverColor: 0x5a5a5a,
    borderColor: 0x888888,
    icon: "🎩",
    category: "person",
    greeting: "Ah, Paris... Savour the moment.",
  },
];
